# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "E:\\Work\\Projects\\CustomerOrders"
      dockerfile: "CustomerOrders/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CustomerOrders.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "customerorders:dev"
    ports: []
    volumes:
    - "E:\\Work\\Projects\\CustomerOrders\\CustomerOrders:/app:rw"
    - "E:\\Work\\Projects\\CustomerOrders:/src:rw"
    - "C:\\Users\\Omino\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
