services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Str0ngP@ssword123!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app-network
  api:
    container_name: customerorders-api
    build:
      context: .
      dockerfile: CustomerOrders/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Connection=Server=db;Database=CustomerOrdersDb;User=sa;Password=Str0ngP@ssword123!;TrustServerCertificate=true;
    networks:
      - app-network

volumes:
  sqlvolume:

networks:
  app-network: